In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
#converting categorical to numerical value
dataset=pd.get_dummies(dataset,dtype=int, drop_first=True)

In [5]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dataset=dataset.drop("User ID",axis=1)

In [7]:
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [8]:
dataset["Purchased"].value_counts()


Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [10]:
indep.shape

(400, 3)

In [11]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [50, 100],
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}

# Store the best model under grid parameter; f1_weighted can be suited for imbalanced data
grid = GridSearchCV(RandomForestClassifier(random_state=0), param_grid, 
                    refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')


# Fitting the model for grid search
grid.fit(X_train, y_train)


Fitting 5 folds for each of 64 candidates, totalling 320 fits


GridSearchCV(estimator=RandomForestClassifier(random_state=0), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 10], 'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 100]},
             scoring='f1_weighted', verbose=3)

In [25]:

# Print the best parameters after tuning
#print("Best Parameters:", grid.best_params_)

# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)


# Store cross-validation results
cv_results = grid.cv_results_
# Uncomment to print all cross-validation results
# print(cv_results)

# Using the final best fit model to test X_test
grid_predictions = grid.predict(X_test)
        

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
        

In [27]:
print(cm)

[[78  7]
 [ 4 45]]


In [28]:
# Generate classification report
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [29]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.92      0.93        85
           1       0.87      0.92      0.89        49

    accuracy                           0.92       134
   macro avg       0.91      0.92      0.91       134
weighted avg       0.92      0.92      0.92       134



In [30]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

np.float64(0.9607442977190876)

In [31]:
print(cm)

[[78  7]
 [ 4 45]]


In [32]:
age_input=float(input("Age:"))
salary_input=float(input("salary:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

Age: 90
salary: 9000000000000000
Sex Male 0 or 1: 0


In [33]:
grid.predict([[age_input,salary_input,sex_male_input]])

C:\Anaconda\envs\aiml\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [34]:
dir(clf_report)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [35]:
table=pd.DataFrame.from_dict(re)

In [36]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.260919      0.008971         0.022014        0.005082   
1        0.514861      0.011365         0.026370        0.008162   
2        0.258894      0.014171         0.019622        0.004989   
3        0.697300      0.053630         0.040975        0.005659   
4        0.389090      0.021118         0.027593        0.004176   
..            ...           ...              ...             ...   
59       0.727818      0.083440         0.049811        0.006601   
60       0.388403      0.053644         0.027584        0.004483   
61       0.608093      0.030351         0.037811        0.004107   
62       0.291763      0.012497         0.027452        0.003988   
63       0.481145      0.023756         0.028699        0.009744   

    param_bootstrap param_criterion param_max_depth  param_min_samples_leaf  \
0              True            gini            None                       1   
1              True            gini            None                       1   
2              True            gini            None                       1   
3              True            gini            None                       1   
4              True            gini            None                       2   
..              ...             ...             ...                     ...   
59            False         entropy              10                       1   
60            False         entropy              10                       2   
61            False         entropy              10                       2   
62            False         entropy              10                       2   
63            False         entropy              10                       2   

    param_min_samples_split  param_n_estimators  \
0                         2                  50   
1                         2                 100   
2                         5                  50   
3                         5                 100   
4                         2                  50   
..                      ...                 ...   
59                        5                 100   
60                        2                  50   
61                        2                 100   
62                        5                  50   
63                        5                 100   

                                               params  split0_test_score  \
0   {'bootstrap': True, 'criterion': 'gini', 'max_...           0.826263   
1   {'bootstrap': True, 'criterion': 'gini', 'max_...           0.826263   
2   {'bootstrap': True, 'criterion': 'gini', 'max_...           0.826263   
3   {'bootstrap': True, 'criterion': 'gini', 'max_...           0.847141   
4   {'bootstrap': True, 'criterion': 'gini', 'max_...           0.847141   
..                                                ...                ...   
59  {'bootstrap': False, 'criterion': 'entropy', '...           0.847141   
60  {'bootstrap': False, 'criterion': 'entropy', '...           0.826263   
61  {'bootstrap': False, 'criterion': 'entropy', '...           0.826263   
62  {'bootstrap': False, 'criterion': 'entropy', '...           0.826263   
63  {'bootstrap': False, 'criterion': 'entropy', '...           0.826263   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.868752           0.851527           0.925272   
1            0.888107           0.851527           0.944161   
2            0.907177           0.870362           0.944161   
3            0.888107           0.870362           0.944161   
4            0.907177           0.870362           0.944161   
..                ...                ...                ...   
59           0.888107           0.832483           0.944161   
60           0.888107           0.870362           0.962636   
61           0.870047           0.870362           0.962636   
62           0.870047           0.870362           0.925272   
63           0.8700